export const LITERARY_GENRES = [
  'Ficção Científica',
  'Fantasia',
  'Romance',
  'Terror',
  'Suspense',
  'Mistério',
  'Aventura',
  'Drama',
  'Biografia',
  'Autobiografia',
  'História',
  'Filosofia',
  'Psicologia',
  'Autoajuda',
  'Negócios',
  'Poesia',
  'Infantil',
  'Juvenil',
  'Religião',
  'Ciência',
  'Tecnologia',
  'Arte',
  'Culinária',
  'Viagem',
  'Humor',
  'Quadrinhos',
  'Mangá',
  'Clássico',
  'Distopia',
  'Policial',
  'Educação',
  'Política',
  'Economia',
  'Sociologia',
  'Outro',
] as const;
